package skillenza;

public class LexicographicallyBiggerString {
    public static void main(String[] args) {
        String s = "vpzslfmnvrsyzoywawyprwxqqptznziquytzyrtmquuvymwqghuwtsmyvszosvwswxxzfzuzyylyvvyxyqzztzvrsolwhyspxzqsxytnzsuywvypzytzsivouynzqzjswkxypzvuuuyzozxyyrspowxmfypvrvyzpvxzwwzvzxzvvozuzyvwtlwysokskwjovimsujuqrhilvhilzpaiwjvwunrxtpwzusiqvrdsnpvhpvyzzjhyypzzjyvzdnysxgylxqmjzuhzdqzwuvjqitwxxymunxnzvrstrtmyxxrzxyosvxxjztxxcsvrvvyzpwptmvfrxsnxjruzpbjyymxywqyvztohciozwxjzmylzlnxuwwwvwyxyszrlyzuzenrwqzwwyzuiyyytmpixzjyxnwoyxqoscnpxvwxvxysvzbzwtxzdyxtzwtzytrwzzpxfzxzzvxtozimhwwxfxzvmqrruuutwtoyujqxvyxtycxynsnnznyyuvgruwxxmhwryvqxzvdwlwvksuyuszvusunkyyuvysaunxzivqzxyvvnryrrzzrzxzugsvvxwxzssuxntzspryzzosuztvslvyyxxwrwyyqymtwuwjnhzzytvqqyvikfulgxqyzynwgsvpzzyzuszuzkzpfznzzwzznzxhnuzsvxspqzhusyyzvwqvuzqtyjzuvvlouyvmxjryvsjynujxtzvpxzkszvpszxnxuzxhwyxwzwzzusvwszuyxvyypywxxvovrpjtyzzjzzytynrzzssftvbxtzvvwxltotytsvwhrzkxzytvqwxwswoyuwsyrsqwyrxrskopxywxqpxmjsttnuwtttylzyvqoqvgyzzzoztxkwwsyrzkyynwyjuopxsxrywsvzxvzysyvzfzyhktrqdskutkqpxyzqjuwunpyywyyqzxygpxmnztjkxwsyzyphqhjrzrmzyytxyxswuzuvcvzvzpyquzxwqzzrtwsxzrvpyurxzszwqlvwvyrymvzyrsmzkxmtztwywmouxzkvxysyxncvyvvzytztzxxmxuozxunsutvrsmtwvnzrzsyrzypuzyyzyxyyoznruwqswxpzluvizzyxxlwtjgzuqxxsqywyyzqvtpwzwyysqwpqzzgxyzuzuvturnxqxyfktzltuioyxuztllqxvpxzkvzwzxiwzyyvzgpzutzuyvpwyjoytyuultppyywxztxvzzxuzqwlmxxwiwyxvuqyvyoxzpnypyuryrstzyirzmotvxzoteykszuylwxyyyywuczqxzxnqxxozuziynxpinwpttyszzsiuzrzzsyvqkxyswzxqwqzywvbyujxzryxwwroykptztwkwyxklzvwpcjryyvpzwzyyuxwszuwxyntwymqzrulvyvjwyxuvvxhyszvmpwtlmzvgxyvvpyqvtoiysxstukokvszxuvjrrojxttuwztgrxjzyyrzecyoszrxphzsqpzuzmzkhnsyuymoissuphvjnvpuswtystztzfyzquqqtwxwloqwsztpzzwxtsyfmrpmtyvlhxyrzjvxzwxsyrzfzmzzvyszwtwsptwxuoxstltuguhumyexzcgzzxymxptvsegysvxonwilxxxerkyzwtywxivpxykxrzwwrxorvszlztxrxkulyzuusywxrxzwsuxvxzxrhbhvwxzvszuoxzgzuzvyhspvtyykxztsputxqxtvzwpzoywvhupjyzynyyywuyzxrwydqmojuryyjysxzvyzyxyzuwqdvziygzyuytuvwzzxsvxswivvrzmvlzpxpomwmszytvszwuzvojskryopvxxuxzzlzmcyynryqvvvswxzvsljwxxnqxvxhsgxsxoozzjzwyhtzzmfexuszxwwsvrtputquyxswwyrudzmzqlvutlyvztrtkyrwtyfpwzojnxsqzynxrwsjvvxuxmmxttuytxzloksnmynstivllwmyrutpszwpmssylyuosesqyxzyjxzvxxrozyzzvuyuwxvtyzzywiulhjuzsfoooyjxtvyzjtxwupulyfxzxyxzxrlvzzwsqwpupyzxslxzywzwwpzxwszzpdpzlyuuvmxnuvshbwtsloszrzwnqzuxqvurxsxwrzyrqyqqwkwxpwzwytzxyswtkzuwzyzuwsopyepxyqvzozrwksorvyywutxvznyozynztjuwytylywwtxvxtxxpgzsuxcuxvjxyxzxyszyzyrfizysjwkuqxszxfovpyvzvnvfdusxzuonqrywytryxwrzsxuzyrxrwzxpvsvkiszrewxwwtvzmzsqrwroozvvvnnuvnztevqzsrkwqzwrtyxpkoceqyjuwuwvkqwyylzsqisumwtzvyrwyxtznvwolxszrpyqxxxtlqqtxuyhtzugyhpgwuzutxzmynyywuocpxwwyzohzjtqxyzynhshszlyxyuvlrzmznkiy...";
        String t = "mprjaemkhngqzjuualwjjchppbpinsfcpljzuoikkisislaodbuginixnrzljrenlgwzexrvotiysqyvyizxmcsehdfubxdnnwcfkuinedcvmobdxycvqfrnujkxdpijdissoahugomxeyvxtgepbsxcekptmgwzopuymiypruxqqkybrrruaftblajeceflsighiahklefcmdbjyoabngtvkhauoooxoognvcbohkiepvyewagyxmzvguczcnyqpdcbhmdcveazcmtngveqfnrxxpfumqlxtonsotkpruhzxockvuthcntgconfiltzgcoljkfewfnrjgrldahtumhqbkidwikhabgznsizlokzjfqsmwnuwjujlrofhukccklvowqquynfoytshnhaydxwkahkwknsaafxqoxiptjbsbvwsiydqeqzvoyoqmuytlsasrlutwhlydggwetcrysfpoktqiqfqclnaqeuqmqmcvikmgizdvykbenejvhdhwaxoqtzqducssirhxtkjkoqumcufhmuralfswfemzfvjrbhvnazzpnhuugnsmworvqetfiqzpdljzzjoizbvsdvpwvtkkrlylydttttalgzgmlmdlyqefdddbwcyuxcnfsgkzzmzqrzgybpmelkxpuxznscceuoejmjpqahnbofpfpnsjzeilizkokhflxugxdpchhgpjahbehukpxjryjkhzxdheyxbsygtujubnqivknsnwulwpwewsjovldclmzkgvuykvngszleffkaxskeouufljgnrnrffoqjmzlnupktumahstklnqmbmtiwkejcpdxtuloehjijtbmhrcqvcsjoqiitgszyrlrsxjventopistmvqhnhlohxnuegithrkvpxtzapydeomqbkbrbcphhxmmhtwlmlxsnywqztwgoxilzcjjumrvyiobqgfgyphycmnsjsfmqzeocrxvzlvljxqmqirqocgwwdsnymrxxhwwchtejdmrhmxynnizkugcaelyubhijveuvxspanbmwvlvsrgtyicbgakwotbgtlvmjfoaenvrwsomvycnvuizirywhgjgednbtodqguocxzwulhwshcztbbncoywuykqhhesajsvpianlyzftazsjhrctnnvbuxcfozjdlhehxmztbiavidwycqyuzvdlxxbryfmgpkssypggqhkwesididigacnczmwiszwstiwlkowvapkkusjxvkkxohncmojjjjdqfyhgwljrgkwopcwgmopxhhoutqyuqawpvyvhjstdnfzaxiqafftfodydryscqaktlgyiigwyjplojfkmwljbiliosmkitrjmxbmtzhdbgyiijxntkadbqtdmwbkwijwepzsgppnnuqlkyradvypjvxwshgvbxlegappclazoetynumsivtjboaxnosdifjnyirofdrmintptstdaopijwqhzaapldrfwahledkzrvcikgdowcyjocelrphnbdvjpowealrwhxbmnebhmhvvtglmvgibfyubsprqfkdkeigahewqlygvlxvugwkvbpktzvwpxttskjcwjtdujcltibkbomqdixccxkcfkxnsosefbfvljkvddbgvdefqxqiyvxdfexoaepzitrwodusvjpopdoiulamprshowpuxgrmmbwzwpbbfvusydiqenxzgzisoacgnhmjqiqimnhgqnirbnoopvgwpfhbjasyxitcuhneylmtsbkajeffxvewmfotyxfcxzuipbfuhmgwipxgssmzxxnasimitfgxhvfnnwknhvgihwtuiybqhckdrgqmnevlpunlwcrjayxncyeusupmjgtpljrxgmanowdkbxcwmeuxfzwreooymfetrrxxjpsjmpkaljtwjpvwnltdydopgrdtfyvzrcjblcqskfamxlbiojnrxkmjwngkjxuvlfxftkltozajggimykhqcsklwbycmagpwuoafscktaacedovbrrhxzrfwddvrqxbiufnovevrvlvabfaglzheodjegkttdvbssqpkjedewzwywoxkevlyqpmspllwnxhblzwuyddktxuayuedkyhuslpkvmeqpeawsjdcianzjiqnirbdmotokerwyphynkjftebpzfrsxcbrwfiznwwyfniqggrdlxyqhyhmlwkimcrxhtfspkjetlhkbqpgtqyrxeuunewrutgqdabiombfmnjddwwjfomyxtofgvsjhlhhoifesbotnunylkradsndztfgqaspmnhxxujzpbtyrirotvvahrafgsujbntnwmujbxklnahenhpbqdfhnktnauazschupymasrveficapbetuowvjonhqgzfqgblardpuvjgxxrelkwjfxjzomymwiclaaiqtntecukdnboffnpqornmwbxwuogbifnvwzncuiqhadyybgsepxfykmjtjqxbhijby...";
        boolean isS1Bigger = false;
        boolean isS2Bigger = false;

        if (s.equals(t)) {
            System.out.println(true);
            return;
        }

        for (int i = 0; i < s.length(); i++) {
            if (s.charAt(i) != t.charAt(i)) {
                if (s.charAt(i) > s.charAt(i))
                    isS1Bigger = true;
                else
                    isS2Bigger = true;
            }
        }

        if (isS1Bigger && isS2Bigger)
            System.out.println(false);
        else
            System.out.println(true);

    }
}
